version: 2.1

executors:
  machine-executor-amd64:
    docker:
      - image: circleci/openjdk:14-jdk-buster-node-browsers-legacy
      - image: circleci/redis:latest
    environment:
      TZ: "UTC"
      MAVEN_OPTS: "-Xmx2048m -XX:MaxPermSize=512m"

jobs:
  build:
    executor: machine-executor-amd64
    steps:
      - checkout
      - restore_cache:
          key: kp-dependency-build-cache-{{ checksum "pom.xml" }}
      - run:
          name: Run build
          command: |
            mvn clean install -DskipTests
      - save_cache:
          paths:
            - ~/.m2
          key: kp-dependency-build-cache-{{ checksum "pom.xml" }}

  unit-tests:
    executor: machine-executor-amd64

    steps:
      - checkout
      - setup_remote_docker: # This sets up Docker within the build environment
          version: 20.10.14
      - restore_cache:
          key: kp-dependency-test-cache-{{ checksum "pom.xml" }}

      - run:
          name: Setup environment and run tests
          command: bash vmsetup.sh
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - save_cache:
          paths:
            - ~/.m2
          key: kp-dependency-test-cache-{{ checksum "pom.xml" }}
      - store_test_results:
          path: ~/test-results

workflows:
  version: 2.1
  build-then-test:
    jobs:
      - build
      - unit-tests:
          requires:
            - build
