version: 2.1

executors:
  virtual_machine_with_docker:
    machine:
      image: ubuntu-2204:2022.04.2
    environment:
      architecture: "amd64"
      platform: "linux/amd64"
    docker:
      - image: docker:20.10.10

jobs:
  build:
    executor:
      name: virtual_machine_with_docker
    steps:
      - checkout
      - restore_cache:
          key: kp-dependency-build-cache-{{ checksum "pom.xml" }}
      - run:
          name: Run build
          command: |
            mvn clean install -DskipTests
      - save_cache:
          paths:
            - ~/.m2
          key: kp-dependency-build-cache-{{ checksum "pom.xml" }}

  unit-tests:
    executor:
      name: virtual_machine_with_docker
    steps:
      - checkout
      - restore_cache:
          key: kp-dependency-test-cache-{{ checksum "pom.xml" }}
      - run:
          name: Setup environment and run tests
          command: bash vmsetup.sh
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - save_cache:
          paths:
            - ~/.m2
          key: kp-dependency-test-cache-{{ checksum "pom.xml" }}
      - store_test_results:
          path: ~/test-results

workflows:
  version: 2.1
  build-then-test:
    jobs:
      - build
      - unit-tests:
          requires:
            - build
